### ISSUE TITLE
Using genome argument in getExpressionEstimates converts numeric to char

### ISSUE THREAD

**Issue by mikegilchrist** [acope3/RibModelFramework#370]
assigning a genome object to the 'genome' argument in getExpressionEstimates() results in the values returned being characters rather than a mixture of characters (geneID) and numeric.

**Comment by acope3** [comment]
Good catch. I likely missed it because I don't usually work with these parameters until after my runs are complete and I'm reading the results from a file. I think this behavior is because the data structures being used are matrices, which will cast everything to the same data type. Changing to data frames should resolve this issue.

**Comment by acope3** [comment]
Issue resolved as part of pull request #374
